"""Report generators: analysis plan, validation, citation, run reports, and reportlets."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_BIDS_LABEL_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


def _sanitize_bids_label(value: str, label_name: str) -> str:
    """Validate and sanitize a BIDS label (subject/session/run) to prevent path traversal."""
    if not value or not _BIDS_LABEL_RE.match(value):
        raise ValueError(f"Invalid {label_name} '{value}': must match [a-zA-Z0-9_-]+")
    return value


def generate_analysis_plan(plan: dict[str, Any], outdir: Path) -> Path:
    """Generate analysis_plan.md from compiled plan."""
    lines = [
        "# fNIRS Analysis Plan",
        "",
        f"**Flow ID:** {plan.get('flow_id', 'N/A')}",
        f"**Name:** {plan.get('name', 'N/A')}",
        f"**Description:** {plan.get('description', 'N/A')}",
        "",
        "## Preprocessing Chain",
        "",
    ]

    for step in plan.get("preprocessing_atoms", []):
        lines.append(f"- **{step.get('atom_id', 'N/A')}** ({step.get('atom_type', 'N/A')})")
        if step.get("parameters"):
            lines.append(f"  - Parameters: `{json.dumps(step['parameters'])}`")

    lines.extend(
        [
            "",
            "## Analysis Chain",
            "",
        ]
    )

    for step in plan.get("analysis_atoms", []):
        lines.append(f"- **{step.get('atom_id', 'N/A')}** ({step.get('atom_type', 'N/A')})")
        if step.get("parameters"):
            lines.append(f"  - Parameters: `{json.dumps(step['parameters'])}`")

    lines.extend(
        [
            "",
            "## Execution",
            "",
            f"- Total steps: {plan.get('execution', {}).get('total_steps', 'N/A')}",
            f"- Flow ID: {plan.get('flow_id', 'N/A')}",
            "",
            f"*Generated by fnirs-flow on {datetime.now(timezone.utc).isoformat()}*",
        ]
    )

    path = outdir / "analysis_plan.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_validation_report(
    errors: list[str],
    warnings: list[str],
    risks: list[dict[str, Any]],
    outdir: Path,
) -> Path:
    """Generate validation_report.md."""
    lines = [
        "# Validation Report",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "",
    ]

    if errors:
        lines.append(f"## Errors ({len(errors)})")
        lines.append("")
        for e in errors:
            lines.append(f"- {e}")
        lines.append("")

    if warnings:
        lines.append(f"## Warnings ({len(warnings)})")
        lines.append("")
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")

    if risks:
        lines.append(f"## Risks ({len(risks)})")
        lines.append("")
        for r in risks:
            severity = r.get("severity", "unknown")
            lines.append(f"- [{severity}] {r.get('message', '')}")
        lines.append("")
    else:
        lines.append("## Risks\n\nNo risks identified.\n")

    path = outdir / "validation_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_run_report(
    batch_summary: dict[str, Any],
    outdir: Path,
) -> Path:
    """Generate run_report.md from batch execution results."""
    lines = [
        "# Run Report",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Summary",
        "",
        f"- Total runs: {batch_summary.get('total', 0)}",
        f"- Successful: {batch_summary.get('successful', 0)}",
        f"- Failed: {batch_summary.get('failed', 0)}",
        "",
    ]

    failed_ids = batch_summary.get("failure_ids", [])
    if failed_ids:
        lines.append("## Failed Runs")
        lines.append("")
        for fid in failed_ids:
            lines.append(f"- {fid}")
        lines.append("")

    path = outdir / "run_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# ============================================================================
# Reportlets: subject/session/run granularity
# ============================================================================


def generate_subject_reportlet(
    subject: str,
    runs: list[dict[str, Any]],
    outdir: Path,
) -> Path:
    """Generate a subject-level reportlet."""
    subject = _sanitize_bids_label(subject, "subject")
    lines = [
        f"# Subject Report: {subject}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        f"**Total runs:** {len(runs)}",
        "",
        "## Run Summary",
        "",
        "| Session | Run | Status | Steps |",
        "|---------|-----|--------|-------|",
    ]
    for r in runs:
        lines.append(
            f"| {r.get('session', '')} | {r.get('run', '')} | "
            f"{r.get('status', '')} | {len(r.get('steps_completed', []))} |"
        )
    lines.append("")

    subject_dir = outdir / f"sub-{subject}"
    subject_dir.mkdir(parents=True, exist_ok=True)
    path = subject_dir / f"sub-{subject}_desc-subject_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_session_reportlet(
    subject: str,
    session: str,
    runs: list[dict[str, Any]],
    outdir: Path,
) -> Path:
    """Generate a session-level reportlet."""
    subject = _sanitize_bids_label(subject, "subject")
    session = _sanitize_bids_label(session, "session")
    lines = [
        f"# Session Report: {subject} / {session}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        f"**Total runs:** {len(runs)}",
        "",
        "## Runs",
        "",
        "| Run | Status | Steps |",
        "|-----|--------|-------|",
    ]
    for r in runs:
        lines.append(f"| {r.get('run', '')} | {r.get('status', '')} | {len(r.get('steps_completed', []))} |")
    lines.append("")

    session_dir = outdir / f"sub-{subject}" / f"ses-{session}"
    session_dir.mkdir(parents=True, exist_ok=True)
    path = session_dir / f"sub-{subject}_ses-{session}_desc-session_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_run_reportlet(
    subject: str,
    session: str,
    run: str,
    run_data: dict[str, Any],
    outdir: Path,
) -> Path:
    """Generate a run-level reportlet."""
    subject = _sanitize_bids_label(subject, "subject")
    session = _sanitize_bids_label(session, "session")
    run = _sanitize_bids_label(run, "run")
    lines = [
        f"# Run Report: {subject} / {session} / {run}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        f"**Status:** {run_data.get('status', 'unknown')}",
        "",
        "## Steps Completed",
        "",
    ]
    for step in run_data.get("steps_completed", []):
        lines.append(f"- {step}")

    if run_data.get("errors"):
        lines.extend(["", "## Errors", ""])
        for err in run_data["errors"]:
            lines.append(f"- {err}")

    lines.append("")

    run_dir = outdir / f"sub-{subject}" / f"ses-{session}" / f"run-{run}"
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / f"sub-{subject}_ses-{session}_run-{run}_desc-run_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_all_reportlets(
    planned_runs: list[dict[str, Any]],
    outdir: Path,
) -> list[Path]:
    """Generate subject/session/run reportlets for all planned runs.

    Groups runs by subject and session, then generates:
    - One subject-level reportlet per subject
    - One session-level reportlet per subject/session
    - One run-level reportlet per run

    Returns list of generated report paths.
    """
    # Group by subject, then by session
    by_subject: dict[str, list[dict[str, Any]]] = {}
    by_session: dict[tuple[str, str], list[dict[str, Any]]] = {}

    for run in planned_runs:
        subj = run.get("subject", "")
        sess = run.get("session", "")
        by_subject.setdefault(subj, []).append(run)
        by_session.setdefault((subj, sess), []).append(run)

    paths: list[Path] = []

    # Subject reportlets
    for subj, runs in by_subject.items():
        if subj:
            paths.append(generate_subject_reportlet(subj, runs, outdir))

    # Session reportlets
    for (subj, sess), runs in by_session.items():
        if subj and sess:
            paths.append(generate_session_reportlet(subj, sess, runs, outdir))

    # Run reportlets
    for run in planned_runs:
        subj = run.get("subject", "")
        sess = run.get("session", "")
        run_name = run.get("run", "")
        if subj and sess and run_name:
            paths.append(generate_run_reportlet(subj, sess, run_name, run, outdir))

    return paths
