// Generated by tools/schema/generate_openapi.py. Do not edit manually.
// Source of truth: fnirs_flow.api.app:app OpenAPI schema.

export interface AIDraftEnvelope {
  "status": string;
  "draft": AIDraftFlow;
}

export interface AIDraftFlow {
  "flow_id": string;
  "name": string;
  "description"?: string;
  "flow_atoms"?: Array<Record<string, unknown>>;
  "edges"?: Array<Record<string, unknown>>;
  "metadata"?: Record<string, unknown>;
}

export interface AIDraftSettings {
  "mode"?: string;
  "provider"?: string;
  "base_url"?: string;
  "model"?: string;
  "organization"?: string;
  "project"?: string;
  "temperature"?: number;
  "max_tokens"?: number;
  "timeout_seconds"?: number;
  "api_key_present"?: boolean;
}

export interface AIDraftValidation {
  "status": string;
  "flow_id": string;
  "valid": boolean;
  "errors"?: Array<string>;
  "warnings"?: Array<string>;
  "risks"?: Array<Record<string, unknown>>;
  "readiness": ReadinessResult;
}

export interface ArtifactSummary {
  "artifact_id"?: string;
  "type": string;
  "uri"?: string;
  "path"?: string;
  "resolved_path"?: string;
  "relative_path"?: string;
  "checksum"?: string;
  "exists"?: boolean;
  "atom_id"?: string;
  "step_id"?: string;
}

export interface AtomResultSummary {
  "atom_id": string;
  "status": string;
  "output_handles"?: Record<string, unknown>;
  "artifacts"?: Array<ArtifactSummary>;
  "warnings"?: Array<string>;
  "error"?: string | unknown;
}

export interface AtomTemplate {
  "id": string;
  "atom_type": string;
  "display_name": string;
  "category": string;
  "operation": string;
  "description"?: string;
  "default_config"?: Record<string, unknown>;
  "parameter_options"?: Record<string, unknown>;
  "parameter_specs"?: Record<string, unknown>;
  "default_readiness_status"?: string;
  "default_execution_scope"?: string;
  "input_ports"?: Array<PortDescription>;
  "output_ports"?: Array<PortDescription>;
  "evidence_refs"?: Array<string>;
  "origin"?: string;
  "reference"?: string;
  "tags"?: Array<string>;
  "flow_atom_blueprint"?: Record<string, unknown>;
  "implementation_module"?: string | null;
  "implementation_callable"?: string | null;
  "implementation_status"?: string;
  "capability_manifest"?: Record<string, unknown> | null;
  "operation_contract"?: OperationContract | unknown;
}

export interface AuthorInfo {
  "id"?: string;
  "display_name"?: string;
}

export interface BackendDescription {
  "backend_id": string;
  "class_path": string;
  "dependency_profile_id"?: string | unknown;
  "display_name": string;
  "description"?: string;
  "is_available": boolean;
  "is_loaded": boolean;
}

export interface BranchInfo {
  "name": string;
  "commit_id": string;
  "is_current"?: boolean;
}

export interface BundleStatus {
  "project_id": string;
  "package_path"?: string;
  "storage_format"?: string;
  "revision"?: number;
  "saved_at"?: string;
  "save_reason"?: string;
  "size_bytes"?: number;
  "integrity_status"?: string;
  "last_verified_at"?: string | unknown;
  "verification_scope"?: string | unknown;
  "integrity_error"?: string | unknown;
  "dirty"?: boolean;
  "busy_operation"?: string | unknown;
  "lock_owner"?: string | unknown;
  "versions"?: Array<Record<string, unknown>>;
}

export interface CheckoutResponse {
  "flow": Record<string, unknown>;
  "target": string;
}

export interface CommitIdResponse {
  "commit_id": string;
}

export interface CommitLogEntry {
  "commit_id": string;
  "parents"?: Array<string>;
  "semantic_flow_hash"?: string;
  "message"?: string;
  "author"?: AuthorInfo;
  "created_at"?: string;
  "reason"?: string;
}

export interface CompileResult {
  "flow_id": string;
  "revision"?: number;
  "steps": number;
  "layers": number;
  "output_files"?: Array<string>;
  "dag_layers"?: Array<Array<Record<string, unknown>>>;
  "atoms"?: number;
  "atom_types"?: Array<string>;
}

export interface DatasetRead {
  "dataset_id": string;
  "name": string;
  "source_kind": string;
  "url"?: string;
  "doi"?: string;
  "citation"?: string;
  "license"?: string;
  "description"?: string;
  "folder_name"?: string;
}

export interface DesignCommit {
  "schema_version"?: string;
  "commit_id"?: string;
  "parents"?: Array<string>;
  "design_object_id"?: string;
  "semantic_flow_hash"?: string;
  "message"?: string;
  "author"?: AuthorInfo;
  "created_at"?: string;
  "reason"?: string;
  "metadata"?: Record<string, unknown>;
}

export interface DesignHistoryStatus {
  "head"?: Record<string, unknown> | unknown;
  "branches"?: Array<Record<string, unknown>>;
  "dirty"?: boolean;
}

export interface DiffChange {
  "kind": "node_added" | "node_removed" | "node_changed" | "edge_added" | "edge_removed" | "edge_changed" | "flow_hash_changed";
  "node_id"?: string | unknown;
  "edge_id"?: string | unknown;
  "path"?: string | unknown;
  "before"?: unknown;
  "after"?: unknown;
}

export interface DiffResult {
  "from_commit": string;
  "to_commit": string;
  "from_flow_hash": string;
  "to_flow_hash": string;
  "changes"?: Array<DiffChange>;
}

export interface DiscoverResult {
  "dataset_id": string;
  "files": number;
  "runs": number;
  "local_root": string;
  "source_url"?: string;
  "metadata_tables"?: number;
  "processed_hb"?: Record<string, unknown>;
}

export interface DryRunResult {
  "total_runs": number;
  "planned_runs"?: Array<Record<string, unknown>>;
  "summary"?: Record<string, unknown>;
}

export interface EmptyMarkerSpec {
  "category": string;
  "input_schema": string;
  "output_schema": string;
  "label": string;
  "atom_id": string;
  "template_id": string;
}

export interface ExampleFlowSummary {
  "id": string;
  "label": string;
}

export interface ExecuteResult {
  "attempt_id"?: string;
  "total_runs": number;
  "successful": number;
  "failed": number;
  "runs"?: Array<RunSummary>;
  "failure_ids"?: Array<string>;
}

export interface ExecutionJobRead {
  "attempt_id": string;
  "project_id": string;
  "commit_id"?: string;
  "snapshot_id"?: string;
  "status": string;
  "created_at": string;
  "started_at"?: string;
  "completed_at"?: string;
  "recovery_count"?: number;
  "cancel_requested"?: boolean;
  "result"?: ExecuteResult | unknown;
  "error"?: string | unknown;
}

export interface ExportRequest {
  "profile"?: string;
  "snapshot_id"?: string | unknown;
  "attempt_id"?: string | unknown;
  "include_history"?: boolean;
}

export interface ExportResult {
  "package_path": string;
  "size_bytes": number;
  "profile"?: string;
  "contents"?: Array<string>;
}

export interface FlowChecklist {
  "scenario_id": string;
  "label": string;
  "description"?: string;
  "version": string;
  "steps"?: Array<FlowChecklistStep>;
}

export interface FlowChecklistStep {
  "slot_id": string;
  "label": string;
  "required": boolean;
  "recommended_template_ids"?: Array<string>;
  "recommended_atom_types"?: Array<string>;
  "default_template_id"?: string;
  "alternative_template_ids"?: Array<string>;
  "input_requirements"?: Array<string>;
  "depends_on"?: Array<string>;
  "allow_empty_marker"?: boolean;
  "category"?: string;
  "guidance"?: string;
}

export interface FlowChecklistSummary {
  "scenario_id": string;
  "label": string;
  "description"?: string;
  "version": string;
  "step_count": number;
}

export interface FlowUpdate {
  "flow": Record<string, unknown>;
  "debounce"?: boolean;
}

export interface FolderEntry {
  "name": string;
  "path": string;
  "has_children": boolean;
}

export interface GenerateAIDraftRequest {
  "scenario": "task" | "resting_state" | "machine_learning" | "real_world" | "hyperscanning" | "multi_site";
  "study_name"?: string;
  "data_format"?: string;
  "conditions"?: Array<string>;
  "assumptions"?: Array<string>;
  "user_confirmations"?: Array<string>;
  "ai_settings"?: AIDraftSettings | unknown;
}

export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}

export interface HealthStatus {
  "status": string;
  "version": string;
}

export interface HistoryMigrationReport {
  "snapshots_imported"?: number;
  "snapshots_skipped"?: number;
  "revisions_imported"?: number;
  "revisions_skipped"?: number;
  "objects_deduplicated"?: number;
  "warnings"?: Array<string>;
  "errors"?: Array<string>;
  "success": boolean;
}

export interface ImportStatus {
  "imported": boolean;
  "read_only": boolean;
  "quarantined_atoms"?: Array<string>;
  "relinked"?: boolean;
  "data_root"?: string;
  "dataset_id"?: string;
}

export interface LocalFolderList {
  "current"?: string;
  "parent"?: string;
  "folders"?: Array<FolderEntry>;
}

export interface OperationContract {
  "canonical_operation": string;
  "execution_scope": string;
  "capabilities"?: Array<string>;
  "supported_backends"?: Array<string>;
  "handler_backends"?: Array<string>;
  "artifact_contract"?: Record<string, unknown>;
  "allow_reviewed_noop"?: boolean;
}

export interface PackageProfile {
  "profile_id": string;
  "name": string;
  "description": string;
  "include_patterns"?: Array<string>;
}

export interface ParticipantTableImportRequest {
  "path": string;
  "table_kind"?: string;
  "id_column"?: string;
  "include_column"?: string;
  "group_column"?: string;
  "label_column"?: string;
  "site_column"?: string;
  "scanner_column"?: string;
  "covariate_columns"?: Array<string>;
  "session_column"?: string;
  "timepoint_column"?: string;
  "pair_id_column"?: string;
  "dyad_id_column"?: string;
  "participant_role_column"?: string;
  "delimiter"?: string;
  "encoding"?: string;
}

export interface ParticipantTableImportResult {
  "table_kind": string;
  "rows": number;
  "columns"?: Array<Record<string, unknown>>;
  "manifest"?: Record<string, unknown>;
  "column_role_map"?: Record<string, unknown>;
  "validation_report"?: Record<string, unknown>;
  "preview_rows"?: Array<Record<string, unknown>>;
}

export interface PortDescription {
  "name": string;
  "schema": string;
  "required": boolean;
}

export interface ProjectCreate {
  "name": string;
  "description"?: string;
  "data_root"?: string;
}

export interface ProjectDataFolderList {
  "parent"?: string;
  "folders"?: Array<FolderEntry>;
}

export interface ProjectLockInfo {
  "project_id": string;
  "locked"?: boolean;
  "operation"?: string;
  "holder_id"?: string;
  "acquired_at"?: string;
  "cross_process"?: boolean;
}

export interface ProjectRead {
  "id": string;
  "name": string;
  "description": string;
  "data_root"?: string;
  "flow_id"?: string;
  "package_path"?: string;
  "storage_format"?: string;
  "revision"?: number;
  "integrity_status"?: string;
  "last_verified_at"?: string | unknown;
  "verification_scope"?: string | unknown;
  "integrity_error"?: string | unknown;
  "busy_operation"?: string | unknown;
}

export interface ProjectResults {
  "kind": "qc" | "channel" | "roi" | "group";
  "file_count": number;
  "files"?: Array<ResultFile>;
  "figures"?: Array<ResultFigure>;
}

export interface ProjectSnapshot {
  "snapshot_id": string;
  "revision": number;
  "created_at": string;
}

export interface ProjectStatus {
  "flow_saved"?: boolean;
  "validated"?: boolean;
  "compiled"?: boolean;
  "data_discovered"?: boolean;
  "runnable_runs"?: number;
  "executed"?: boolean;
  "flow_revision"?: number;
  "compiled_revision"?: number;
  "last_attempt_id"?: string;
  "last_execution_status"?: string;
  "read_only"?: boolean;
  "quarantined_atoms"?: Array<string>;
}

export interface ReadinessCheck {
  "name": string;
  "status": string;
  "message"?: string;
}

export interface ReadinessResult {
  "status": string;
  "checks"?: Array<ReadinessCheck>;
}

export interface ResultFigure {
  "path": string;
  "svg": string;
}

export interface ResultFile {
  "path": string;
  "data": unknown;
}

export interface RunSummary {
  "run_id": string;
  "status": string;
  "subject"?: string;
  "session"?: string;
  "run"?: string;
  "started_at"?: string;
  "completed_at"?: string;
  "atom_results"?: Array<AtomResultSummary>;
  "artifacts"?: Array<ArtifactSummary>;
}

export interface ValidationError {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
}

export interface ValidationResult {
  "is_valid": boolean;
  "errors"?: Array<string>;
  "warnings"?: Array<string>;
  "risks"?: Array<Record<string, unknown>>;
}

export interface VersionHistoryEntry {
  "revision": number;
  "saved_at": string;
  "reason": string;
  "current": boolean;
  "path": string;
}

export type ApiPath = keyof typeof API_PATHS;
export const API_PATHS = {
  "/api/ai/draft-flow": true,
  "/api/atom-templates": true,
  "/api/backends": true,
  "/api/datasets": true,
  "/api/dependencies/installations/{task_id}": true,
  "/api/dependencies/installations/{task_id}/cancel": true,
  "/api/dependencies/plans/{plan_id}": true,
  "/api/dependencies/plans/{plan_id}/approve": true,
  "/api/dependencies/plans/{plan_id}/record-approval": true,
  "/api/dependencies/plans/{plan_id}/reject": true,
  "/api/dependencies/resolve": true,
  "/api/dependency-environments": true,
  "/api/dependency-environments/{environment_id}": true,
  "/api/empty-marker-specs": true,
  "/api/example-flows": true,
  "/api/example-flows/{example_id}": true,
  "/api/flow-checklists": true,
  "/api/flow-checklists/{scenario_id}": true,
  "/api/health": true,
  "/api/local-folders": true,
  "/api/package-profiles": true,
  "/api/projects": true,
  "/api/projects/{project_id}": true,
  "/api/projects/{project_id}/ai/confirm-draft": true,
  "/api/projects/{project_id}/ai/draft": true,
  "/api/projects/{project_id}/ai/draft-flow": true,
  "/api/projects/{project_id}/ai/validate-draft": true,
  "/api/projects/{project_id}/attempts": true,
  "/api/projects/{project_id}/attempts/{attempt_id}": true,
  "/api/projects/{project_id}/attempts/{attempt_id}/cancel": true,
  "/api/projects/{project_id}/bind-dataset": true,
  "/api/projects/{project_id}/bundle": true,
  "/api/projects/{project_id}/bundle/restore/{revision}": true,
  "/api/projects/{project_id}/compile": true,
  "/api/projects/{project_id}/data-folders": true,
  "/api/projects/{project_id}/discover-data": true,
  "/api/projects/{project_id}/dry-run": true,
  "/api/projects/{project_id}/execute": true,
  "/api/projects/{project_id}/export-package": true,
  "/api/projects/{project_id}/flow": true,
  "/api/projects/{project_id}/fork": true,
  "/api/projects/{project_id}/history": true,
  "/api/projects/{project_id}/history/branches": true,
  "/api/projects/{project_id}/history/branches/{name}": true,
  "/api/projects/{project_id}/history/checkout": true,
  "/api/projects/{project_id}/history/commits": true,
  "/api/projects/{project_id}/history/commits/{commit_id}": true,
  "/api/projects/{project_id}/history/diff": true,
  "/api/projects/{project_id}/history/initialize": true,
  "/api/projects/{project_id}/history/migrate": true,
  "/api/projects/{project_id}/import-package": true,
  "/api/projects/{project_id}/import-status": true,
  "/api/projects/{project_id}/lock": true,
  "/api/projects/{project_id}/participant-table": true,
  "/api/projects/{project_id}/progress": true,
  "/api/projects/{project_id}/relink-data": true,
  "/api/projects/{project_id}/results/{kind}": true,
  "/api/projects/{project_id}/snapshots": true,
  "/api/projects/{project_id}/status": true,
  "/api/projects/{project_id}/trust-atom/{atom_id}": true,
  "/api/projects/{project_id}/validate": true,
  "/api/projects/{project_id}/version-history": true,
  "/{full_path}": true,
} as const;

export interface GeneratedApiClientOptions {
  baseUrl?: string;
  fetchImpl?: typeof fetch;
}

export function createGeneratedApiClient(options: GeneratedApiClientOptions = {}) {
  const baseUrl = options.baseUrl ?? '';
  const fetchImpl = options.fetchImpl ?? fetch;
  return async function request<T>(path: ApiPath, init: RequestInit = {}): Promise<T> {
    const response = await fetchImpl(`${baseUrl}${path}`, {
      ...init,
      headers: { 'Content-Type': 'application/json', ...init.headers },
    });
    if (!response.ok) throw new Error(`API request failed: ${response.status} ${response.statusText}`);
    return response.status === 204 ? (undefined as T) : (await response.json() as T);
  };
}
