"""Tests for AnalyzIR bidirectional import/export adapters."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from fnirs_flow.adapters.analyzir_export import (
    AnalyzIRScript,
    convert_flow_to_analyzir,
    generate_r_script,
    write_analyzir_mapping_report,
    write_analyzir_script,
)
from fnirs_flow.adapters.analyzir_import import (
    AnalyzIRImportResult,
    import_analyzir,
    parse_analyzir_json,
    parse_analyzir_r_script,
    write_import_report,
)

# ============================================================================
# Fixtures
# ============================================================================

SAMPLE_FLOW_ATOMS = [
    {
        "atom_type": "optical_density",
        "config": {"parameters": {}},
    },
    {
        "atom_type": "tddr_motion",
        "config": {"parameters": {}},
    },
    {
        "atom_type": "bandpass_filter",
        "config": {"parameters": {"l_freq": 0.01, "h_freq": 0.5}},
    },
    {
        "atom_type": "beer_lambert_law",
        "config": {"parameters": {"ppf": 6.0}},
    },
    {
        "atom_type": "block_averaging",
        "config": {"parameters": {"baseline_window": [-5, 0], "response_window": [0, 20]}},
    },
    {
        "atom_type": "scalp_coupling_index",
        "config": {"parameters": {"sci_threshold": 0.8}},
    },
    {
        "atom_type": "unknown_custom_step",
        "config": {"parameters": {}},
    },
]

SAMPLE_R_SCRIPT = """\
# AnalyzIR processing script
data <- load("test_data.snirf")

# Step 1: Convert intensity to optical density
data <- hmrR_Intensity2OD(data)

# Step 2: TDDR motion correction
data <- hmrR_MotionCorrectTD(data)

# Step 3: Bandpass filter
data <- hmrR_BandpassFilt(data, lpf=0.5, hpf=0.01)

# Step 4: Beer-Lambert law
data <- hmrR_OD2Conc(data, DPF=c(6, 6))

# Step 5: SCI QC
data <- hmrR_Sci(data, sciThresh=0.8)

# Save results
save(data, file = "result.RData")
"""

SAMPLE_JSON_CONFIG = {
    "data_path": "test_data.snirf",
    "steps": [
        {"func": "hmrR_Intensity2OD", "params": {}},
        {"func": "hmrR_MotionCorrectTD", "params": {}},
        {"func": "hmrR_BandpassFilt", "params": {"lpf": 0.5, "hpf": 0.01}},
        {"func": "hmrR_OD2Conc", "params": {"DPF": [6, 6]}},
    ],
}


# ============================================================================
# Export Tests
# ============================================================================


class TestAnalyzIRExport:
    """Test AnalyzIR export functionality."""

    def test_convert_flow_to_analyzir_basic(self):
        """Test basic conversion of flow atoms to AnalyzIR script."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        assert isinstance(script, AnalyzIRScript)
        assert len(script.steps) == 6  # 6 mapped atoms
        assert len(script.unmapped_atoms) == 1  # unknown_custom_step

    def test_convert_flow_to_analyzir_step_names(self):
        """Test that step names are preserved."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        step_names = [s.name for s in script.steps]
        assert "optical_density" in step_names
        assert "tddr_motion" in step_names
        assert "bandpass_filter" in step_names
        assert "beer_lambert_law" in step_names
        assert "block_averaging" in step_names
        assert "scalp_coupling_index" in step_names

    def test_convert_flow_to_analyzir_functions(self):
        """Test that AnalyzIR function names are correct."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        func_map = {s.name: s.func for s in script.steps}
        assert func_map["optical_density"] == "hmrR_Intensity2OD"
        assert func_map["tddr_motion"] == "hmrR_MotionCorrectTD"
        assert func_map["bandpass_filter"] == "hmrR_BandpassFilt"
        assert func_map["beer_lambert_law"] == "hmrR_OD2Conc"

    def test_convert_flow_to_analyzir_unmapped(self):
        """Test that unmapped atoms are tracked."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)
        assert "unknown_custom_step" in script.unmapped_atoms

    def test_generate_r_script(self):
        """Test R script generation."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)
        r_content = generate_r_script(script)

        assert "hmrR_Intensity2OD" in r_content
        assert "hmrR_MotionCorrectTD" in r_content
        assert "hmrR_BandpassFilt" in r_content
        assert "hmrR_OD2Conc" in r_content
        assert "# Generated by fnirs-flow" in r_content

    def test_generate_r_script_with_comments(self):
        """Test R script generation with comments."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)
        r_content = generate_r_script(script, include_comments=True)

        assert "# Step 1:" in r_content
        assert "# === Preprocessing Steps ===" in r_content

    def test_generate_r_script_without_comments(self):
        """Test R script generation without comments."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)
        r_content = generate_r_script(script, include_comments=False)

        assert "# Step 1:" not in r_content
        assert "hmrR_Intensity2OD" in r_content

    def test_write_analyzir_script(self):
        """Test writing AnalyzIR R script to file."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        with tempfile.TemporaryDirectory() as tmpdir:
            path = write_analyzir_script(script, Path(tmpdir))
            assert path.exists()
            assert path.name == "fnirs_pipeline.R"

            content = path.read_text(encoding="utf-8")
            assert "hmrR_Intensity2OD" in content
            assert "hmrR_BandpassFilt" in content

    def test_write_analyzir_mapping_report(self):
        """Test writing AnalyzIR mapping report."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        with tempfile.TemporaryDirectory() as tmpdir:
            path = write_analyzir_mapping_report(script, Path(tmpdir))
            assert path.exists()
            assert path.name == "analyzir_export_report.md"

            content = path.read_text(encoding="utf-8")
            assert "Mapped Steps" in content
            assert "Unmapped Atoms" in content
            assert "hmrR_Intensity2OD" in content

    def test_convert_empty_atoms(self):
        """Test conversion with empty atom list."""
        script = convert_flow_to_analyzir([])
        assert len(script.steps) == 0
        assert len(script.unmapped_atoms) == 0

    def test_convert_ica_unmapped(self):
        """Test that ICA motion correction is unmapped."""
        atoms = [{"atom_type": "ica_motion_correction", "config": {"parameters": {}}}]
        script = convert_flow_to_analyzir(atoms)
        assert len(script.steps) == 0
        assert "ica_motion_correction" in script.unmapped_atoms

    def test_r_script_with_data_path(self):
        """Test R script generation with data path."""
        script = convert_flow_to_analyzir(
            SAMPLE_FLOW_ATOMS,
            data_path="test_data.snirf",
            output_dir="outputs/analyzir",
        )

        r_content = generate_r_script(script)
        assert "test_data.snirf" in r_content
        assert "outputs/analyzir" in r_content

    def test_bandpass_params_in_r(self):
        """Test that bandpass filter params are correctly formatted in R."""
        atoms = [
            {
                "atom_type": "bandpass_filter",
                "config": {"parameters": {"l_freq": 0.01, "h_freq": 0.5}},
            }
        ]
        script = convert_flow_to_analyzir(atoms)
        r_content = generate_r_script(script)

        assert "lpf=0.5" in r_content
        assert "hpf=0.01" in r_content

    def test_bll_params_in_r(self):
        """Test that Beer-Lambert law params are correctly formatted in R."""
        atoms = [
            {
                "atom_type": "beer_lambert_law",
                "config": {"parameters": {"ppf": 6.0}},
            }
        ]
        script = convert_flow_to_analyzir(atoms)
        r_content = generate_r_script(script)

        assert "DPF=c(6.0, 6.0)" in r_content


# ============================================================================
# Import Tests
# ============================================================================


class TestAnalyzIRImport:
    """Test AnalyzIR import functionality."""

    def test_parse_analyzir_r_script_basic(self):
        """Test parsing AnalyzIR R script."""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(SAMPLE_R_SCRIPT, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            assert isinstance(result, AnalyzIRImportResult)
            assert len(result.atoms) == 5
            assert result.source_format == "analyzir_r_script"

    def test_parse_analyzir_r_script_atom_types(self):
        """Test that imported atom types are correct."""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(SAMPLE_R_SCRIPT, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            atom_types = [a["atom_type"] for a in result.atoms]
            assert "optical_density" in atom_types
            assert "tddr_motion" in atom_types
            assert "bandpass_filter" in atom_types
            assert "beer_lambert_law" in atom_types
            assert "scalp_coupling_index" in atom_types

    def test_parse_analyzir_r_script_params(self):
        """Test that parameters are correctly imported."""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(SAMPLE_R_SCRIPT, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            bp_atom = next(a for a in result.atoms if a["atom_type"] == "bandpass_filter")
            assert bp_atom["config"]["parameters"]["h_freq"] == 0.5
            assert bp_atom["config"]["parameters"]["l_freq"] == 0.01

    def test_parse_analyzir_r_script_data_path(self):
        """Test that data path is extracted."""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(SAMPLE_R_SCRIPT, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            assert result.data_path == "test_data.snirf"

    def test_parse_analyzir_r_script_missing_file(self):
        """Test parsing non-existent file."""
        result = parse_analyzir_r_script("/nonexistent/pipeline.R")
        assert len(result.warnings) > 0
        assert len(result.atoms) == 0

    def test_parse_analyzir_json_basic(self):
        """Test parsing AnalyzIR JSON config."""
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = Path(tmpdir) / "config.json"
            json_path.write_text(json.dumps(SAMPLE_JSON_CONFIG), encoding="utf-8")

            result = parse_analyzir_json(json_path)

            assert isinstance(result, AnalyzIRImportResult)
            assert len(result.atoms) == 4
            assert result.source_format == "analyzir_json"

    def test_parse_analyzir_json_atom_types(self):
        """Test that imported atom types from JSON are correct."""
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = Path(tmpdir) / "config.json"
            json_path.write_text(json.dumps(SAMPLE_JSON_CONFIG), encoding="utf-8")

            result = parse_analyzir_json(json_path)

            atom_types = [a["atom_type"] for a in result.atoms]
            assert "optical_density" in atom_types
            assert "tddr_motion" in atom_types
            assert "bandpass_filter" in atom_types
            assert "beer_lambert_law" in atom_types

    def test_parse_analyzir_json_data_path(self):
        """Test that data path is extracted from JSON."""
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = Path(tmpdir) / "config.json"
            json_path.write_text(json.dumps(SAMPLE_JSON_CONFIG), encoding="utf-8")

            result = parse_analyzir_json(json_path)

            assert result.data_path == "test_data.snirf"

    def test_parse_analyzir_json_missing_file(self):
        """Test parsing non-existent JSON file."""
        result = parse_analyzir_json("/nonexistent/config.json")
        assert len(result.warnings) > 0

    def test_import_analyzir_r(self):
        """Test import_analyzir with .R file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(SAMPLE_R_SCRIPT, encoding="utf-8")

            result = import_analyzir(r_path)
            assert len(result.atoms) == 5

    def test_import_analyzir_json(self):
        """Test import_analyzir with .json file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = Path(tmpdir) / "config.json"
            json_path.write_text(json.dumps(SAMPLE_JSON_CONFIG), encoding="utf-8")

            result = import_analyzir(json_path)
            assert len(result.atoms) == 4

    def test_import_analyzir_unsupported(self):
        """Test import_analyzir with unsupported format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            txt_path = Path(tmpdir) / "pipeline.txt"
            txt_path.write_text("some content", encoding="utf-8")

            result = import_analyzir(txt_path)
            assert len(result.warnings) > 0

    def test_write_import_report(self):
        """Test writing import report."""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(SAMPLE_R_SCRIPT, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            report_path = write_import_report(result, Path(tmpdir))
            assert report_path.exists()
            assert report_path.name == "analyzir_import_report.md"

            content = report_path.read_text(encoding="utf-8")
            assert "Imported Atoms" in content
            assert "hmrR_Intensity2OD" in content

    def test_import_unknown_function(self):
        """Test importing R script with unknown function."""
        r_script = """\
data <- hmrR_Intensity2OD(data)
data <- hmrR_UnknownFunction(data, param1=1.0)
"""
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(r_script, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            assert len(result.atoms) == 1
            assert len(result.unmapped_functions) == 1
            assert result.unmapped_functions[0]["function"] == "hmrR_UnknownFunction"

    def test_sci_params_import(self):
        """Test that SCI threshold is correctly imported."""
        r_script = 'data <- hmrR_Sci(data, sciThresh=0.7)\n'
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(r_script, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            sci_atom = next(a for a in result.atoms if a["atom_type"] == "scalp_coupling_index")
            assert sci_atom["config"]["parameters"]["sci_threshold"] == 0.7

    def test_bll_params_import(self):
        """Test that DPF is correctly imported from R."""
        r_script = 'data <- hmrR_OD2Conc(data, DPF=c(6.2, 6.2))\n'
        with tempfile.TemporaryDirectory() as tmpdir:
            r_path = Path(tmpdir) / "pipeline.R"
            r_path.write_text(r_script, encoding="utf-8")

            result = parse_analyzir_r_script(r_path)

            bll_atom = next(a for a in result.atoms if a["atom_type"] == "beer_lambert_law")
            assert bll_atom["config"]["parameters"]["ppf"] == 6.2


# ============================================================================
# Round-trip Tests
# ============================================================================


class TestAnalyzIRRoundTrip:
    """Test export -> import round-trip consistency."""

    def test_export_then_import_preserves_atoms(self):
        """Test that export then import preserves the same atom types."""
        # Export
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        with tempfile.TemporaryDirectory() as tmpdir:
            # Write exported R script
            outdir = Path(tmpdir) / "export"
            write_analyzir_script(script, outdir)

            # Import back
            r_path = outdir / "fnirs_pipeline.R"
            result = parse_analyzir_r_script(r_path)

        # Compare atom types (excluding unmapped)
        exported_types = {s.name for s in script.steps}
        imported_types = {a["atom_type"] for a in result.atoms}

        assert exported_types == imported_types

    def test_export_then_import_json_preserves_atoms(self):
        """Test JSON round-trip preserves atom types."""
        # Export to JSON-like format
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        # Create JSON config from exported script
        json_config = {
            "data_path": "test.snirf",
            "steps": [
                {"func": s.func, "params": s.params}
                for s in script.steps
            ],
        }

        with tempfile.TemporaryDirectory() as tmpdir:
            json_path = Path(tmpdir) / "config.json"
            json_path.write_text(json.dumps(json_config), encoding="utf-8")

            result = parse_analyzir_json(json_path)

        exported_types = {s.name for s in script.steps}
        imported_types = {a["atom_type"] for a in result.atoms}

        assert exported_types == imported_types

    def test_export_then_import_preserves_operations(self):
        """Test that operations are preserved through round-trip."""
        script = convert_flow_to_analyzir(SAMPLE_FLOW_ATOMS)

        with tempfile.TemporaryDirectory() as tmpdir:
            outdir = Path(tmpdir) / "export"
            write_analyzir_script(script, outdir)

            r_path = outdir / "fnirs_pipeline.R"
            result = parse_analyzir_r_script(r_path)

        exported_ops = {s.name: s.func for s in script.steps}
        for atom in result.atoms:
            atom_type = atom["atom_type"]
            if atom_type in exported_ops:
                assert atom["source_function"] == exported_ops[atom_type]
