"""Render the CI-owned current-status snapshot after all release gates pass."""

from __future__ import annotations

import argparse
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

JOBS = (
    "core-contract",
    "runtime-mne",
    "runtime-cedalion",
    "webui",
    "package-blackbox",
    "security-release",
)


def package_version() -> str:
    try:
        return version("fnirs-flow")
    except PackageNotFoundError:
        return "unknown"


def render(*, revision: str, run_url: str) -> str:
    job_lines = "\n".join(f"- `{job}`: passed" for job in JOBS)
    return f"""# Current project status

This snapshot is generated by CI after every architecture/release gate passes.

- Package version: `{package_version()}`
- Revision: `{revision}`
- CI run: {run_url}

## Required gates

{job_lines}

The architecture execution plan is complete only when this snapshot is
produced by a successful run. Historical audits under `docs/audit/` are not
the current state.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--revision", required=True)
    parser.add_argument("--run-url", required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(revision=args.revision, run_url=args.run_url), encoding="utf-8")


if __name__ == "__main__":
    main()
