"""Export FastAPI OpenAPI as the source for generated WebUI DTOs."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

OUTPUT = REPOSITORY_ROOT / "generated" / "openapi.json"
TYPES_OUTPUT = REPOSITORY_ROOT / "webui" / "src" / "api" / "generated.ts"


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_ts_type(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_ts_type(schema.get('items', {}))}>"
    if kind == "object":
        return "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(
        str(kind), "unknown"
    )


def _generate_types(document: dict[str, Any]) -> str:
    lines = [
        "// Generated by tools/schema/generate_openapi.py. Do not edit manually.",
        "// Source of truth: fnirs_flow.api.app:app OpenAPI schema.",
        "",
    ]
    schemas = document.get("components", {}).get("schemas", {})
    for name, schema in sorted(schemas.items()):
        if schema.get("type") != "object":
            lines.append(f"export type {name} = {_ts_type(schema)};")
            continue
        required = set(schema.get("required", []))
        lines.append(f"export interface {name} {{")
        for field, definition in schema.get("properties", {}).items():
            optional = "" if field in required else "?"
            lines.append(f"  {json.dumps(field)}{optional}: {_ts_type(definition)};")
        lines.append("}")
        lines.append("")
    lines.append("export type ApiPath = keyof typeof API_PATHS;")
    lines.append("export const API_PATHS = {")
    for path in sorted(document.get("paths", {})):
        lines.append(f"  {json.dumps(path)}: true,")
    lines.append("} as const;")
    lines.extend(
        [
            "",
            "export interface GeneratedApiClientOptions {",
            "  baseUrl?: string;",
            "  fetchImpl?: typeof fetch;",
            "}",
            "",
            "export function createGeneratedApiClient(options: GeneratedApiClientOptions = {}) {",
            "  const baseUrl = options.baseUrl ?? '';",
            "  const fetchImpl = options.fetchImpl ?? fetch;",
            "  return async function request<T>(path: ApiPath, init: RequestInit = {}): Promise<T> {",
            "    const response = await fetchImpl(`${baseUrl}${path}`, {",
            "      ...init,",
            "      headers: { 'Content-Type': 'application/json', ...init.headers },",
            "    });",
            "    if (!response.ok) throw new Error(`API request failed: ${response.status} ${response.statusText}`);",
            "    return response.status === 204 ? (undefined as T) : (await response.json() as T);",
            "  };",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    from fnirs_flow.api.app import app

    document = app.openapi()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    openapi_text = json.dumps(document, indent=2) + "\n"
    types_text = _generate_types(document)
    OUTPUT.write_text(openapi_text, encoding="utf-8")
    TYPES_OUTPUT.write_text(types_text, encoding="utf-8")


if __name__ == "__main__":
    main()
